/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author User
 */
public class addtreeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form addtreeJFrame
     */
    public addtreeJFrame() {
        initComponents();
        jLabel9.setVisible(false);
        idField.setVisible(false);
        add.setSelected(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        namefield = new javax.swing.JTextField();
        sizefield = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        waterfield = new javax.swing.JTextField();
        harvestField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        add = new javax.swing.JRadioButton();
        delete = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        quantityfield = new javax.swing.JTextField();
        alter = new javax.swing.JRadioButton();
        price = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tree Type :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tree Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tree Size :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weather Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("waterAmountPerWeek :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HarvestTime :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(61, 61, 61));
        jComboBox1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        namefield.setBackground(new java.awt.Color(61, 61, 61));
        namefield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        namefield.setForeground(new java.awt.Color(255, 255, 255));
        namefield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, -1));

        sizefield.setBackground(new java.awt.Color(61, 61, 61));
        sizefield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        sizefield.setForeground(new java.awt.Color(255, 255, 255));
        sizefield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(sizefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 70, -1));

        jComboBox2.setBackground(new java.awt.Color(61, 61, 61));
        jComboBox2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "moderate", "Hot", "Cold" }));
        jComboBox2.setBorder(null);
        jComboBox2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboBox2ComponentHidden(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        waterfield.setBackground(new java.awt.Color(61, 61, 61));
        waterfield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        waterfield.setForeground(new java.awt.Color(255, 255, 255));
        waterfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(waterfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 190, -1));

        harvestField.setBackground(new java.awt.Color(61, 61, 61));
        harvestField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        harvestField.setForeground(new java.awt.Color(255, 255, 255));
        harvestField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(harvestField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 150, -1));

        priceField.setBackground(new java.awt.Color(61, 61, 61));
        priceField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        priceField.setForeground(new java.awt.Color(255, 255, 255));
        priceField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 130, -1));

        buttonGroup1.add(add);
        add.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD New Tree");
        add.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addItemStateChanged(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 130, 40));

        buttonGroup1.add(delete);
        delete.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE Existing Tree");
        delete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deleteItemStateChanged(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 170, 40));

        jButton1.setBackground(new java.awt.Color(85, 124, 104));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DONE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 460, 120, 60));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        idField.setBackground(new java.awt.Color(61, 61, 61));
        idField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        idField.setForeground(new java.awt.Color(255, 255, 255));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 120, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 120, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        quantityfield.setBackground(new java.awt.Color(61, 61, 61));
        quantityfield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        quantityfield.setForeground(new java.awt.Color(255, 255, 255));
        quantityfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(quantityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 120, 20));

        buttonGroup1.add(alter);
        alter.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        alter.setForeground(new java.awt.Color(255, 255, 255));
        alter.setText("ADD Tree Quantity");
        alter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                alterItemStateChanged(evt);
            }
        });
        jPanel1.add(alter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 360, -1, 40));

        buttonGroup1.add(price);
        price.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Change Tree Price");
        price.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                priceItemStateChanged(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, -1, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lake_1350x700.jpeg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void addItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addItemStateChanged
        // TODO add your handling code here:
        if (add.isSelected()) {
            jLabel9.setVisible(false);
            idField.setVisible(false);
            namefield.setVisible(true);
            harvestField.setVisible(true);
            priceField.setVisible(true);
            sizefield.setVisible(true);
            waterfield.setVisible(true);
            jComboBox1.setVisible(true);
            jComboBox2.setVisible(true);
            quantityfield.setVisible(true);
            jLabel2.setVisible(true);jLabel3.setVisible(true);jLabel4.setVisible(true);jLabel5.setVisible(true);jLabel6.setVisible(true);jLabel7.setVisible(true);jLabel8.setVisible(true);jLabel10.setVisible(true);
        }
    }//GEN-LAST:event_addItemStateChanged

    private void deleteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deleteItemStateChanged
        // TODO add your handling code here:
        if (delete.isSelected()) {
            jLabel9.setVisible(true);
            idField.setVisible(true);
            namefield.setVisible(false);
            harvestField.setVisible(false);
            priceField.setVisible(false);
            namefield.setVisible(false);
            sizefield.setVisible(false);
            waterfield.setVisible(false);
            jComboBox1.setVisible(false);
            jComboBox2.setVisible(false);
            quantityfield.setVisible(false);
            jLabel2.setVisible(false);jLabel3.setVisible(false);jLabel4.setVisible(false);jLabel5.setVisible(false);jLabel6.setVisible(false);jLabel7.setVisible(false);jLabel8.setVisible(false);jLabel10.setVisible(false);
        }

    }//GEN-LAST:event_deleteItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection c = null;
        int i=0;


        if(add.isSelected() && !namefield.getText().equals("") && !sizefield.getText().equals("") && !waterfield.getText().equals("") && !quantityfield.getText().equals("") && !priceField.getText().equals("") &&!harvestField.getText().equals("") && jComboBox1.getSelectedIndex()!=-1 && jComboBox2.getSelectedIndex()!=-1)
        {    

          try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement ps = c.prepareStatement("insert into items values (?,?,?,?)");
            ps.setString(1, null);
            ps.setString(2, "tree");
            ps.setInt(3, Integer.parseInt(priceField.getText()));
            ps.setInt(4, Integer.parseInt(quantityfield.getText()));
            ps.executeUpdate();
            
            PreparedStatement pst2 = c.prepareStatement("select id from items ORDER BY id DESC LIMIT 1");
            ResultSet rs = pst2.executeQuery();
            while(rs.next())
            {
                i=rs.getInt("id");
            }
            
            PreparedStatement ps1 = c.prepareStatement("insert into trees values(?,?,?,?,?,?,?)");
            ps1.setInt(1,i);
            ps1.setString(2,jComboBox1.getSelectedItem().toString());
            ps1.setString(3, namefield.getText());
            ps1.setInt(4, Integer.parseInt(sizefield.getText()));
            ps1.setInt(5, Integer.parseInt(waterfield.getText()));
            ps1.setString(6,jComboBox2.getSelectedItem().toString());
            ps1.setString(7, harvestField.getText());
            ps1.executeUpdate();
            c.close();
            
        } 
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        else if(delete.isSelected() && !idField.getText().equals(""))
        {
           try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement ps3 = c.prepareStatement("delete from items where id=?");
            ps3.setInt(1, Integer.parseInt(idField.getText()));
            ps3.executeUpdate();
            c.close();   
        } 
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
           
        }
        else if(alter.isSelected() && !idField.getText().equals("") && !quantityfield.getText().equals(""))
        {
            try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement ps4 = c.prepareStatement("update items set quantity = ? where id = ?");
            ps4.setInt(1, Integer.parseInt(quantityfield.getText()));
            ps4.setInt(2, Integer.parseInt(idField.getText()));
            ps4.executeUpdate();
            c.close();   
        } 
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        else if(price.isSelected() && !idField.getText().equals("") && !priceField.getText().equals(""))
        {
            try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement pst4 = c.prepareStatement("update items set Price = ? where id = ?");
            pst4.setInt(1, Integer.parseInt(priceField.getText()));
            pst4.setInt(2, Integer.parseInt(idField.getText()));
            pst4.executeUpdate();
            c.close();   
        } 
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Fill the missing data!");
        }

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alterItemStateChanged
        // TODO add your handling code here:
        if(alter.isSelected())
        {
            idField.setVisible(true);
            quantityfield.setVisible(true);
            jLabel10.setVisible(true);
            jLabel9.setVisible(true);
            namefield.setVisible(false);
            harvestField.setVisible(false);
            priceField.setVisible(false);
            namefield.setVisible(false);
            sizefield.setVisible(false);
            waterfield.setVisible(false);
            jComboBox1.setVisible(false);
            jComboBox2.setVisible(false);
            jLabel2.setVisible(false);jLabel3.setVisible(false);jLabel4.setVisible(false);jLabel5.setVisible(false);jLabel6.setVisible(false);jLabel7.setVisible(false);jLabel8.setVisible(false);
            
        }
    }//GEN-LAST:event_alterItemStateChanged

    private void priceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_priceItemStateChanged
        // TODO add your handling code here:
            idField.setVisible(true);
            jLabel9.setVisible(true);
            jLabel6.setVisible(true);
            priceField.setVisible(true);
            jLabel10.setVisible(false); 
            namefield.setVisible(false);
            quantityfield.setVisible(false);
            harvestField.setVisible(false);
            sizefield.setVisible(false);
            waterfield.setVisible(false);
            jComboBox1.setVisible(false);
            jComboBox2.setVisible(false);
            jLabel2.setVisible(false);jLabel3.setVisible(false);jLabel4.setVisible(false);jLabel5.setVisible(false);jLabel7.setVisible(false);jLabel8.setVisible(false);
    }//GEN-LAST:event_priceItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            namefield.setText("");
            harvestField.setText("");
            priceField.setText("");
            sizefield.setText("");
            waterfield.setText("");
            idField.setText("");
            quantityfield.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jComboBox2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox2ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ComponentHidden

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton add;
    private javax.swing.JRadioButton alter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton delete;
    private javax.swing.JTextField harvestField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefield;
    private javax.swing.JRadioButton price;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JTextField sizefield;
    private javax.swing.JTextField waterfield;
    // End of variables declaration//GEN-END:variables
}
