/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author User
 */
public class addtoolJFrame extends javax.swing.JFrame {

    /**
     * Creates new form addtoolJFrame
     */
    public addtoolJFrame() {
        initComponents();
        jLabel00.setVisible(false);
        idField.setVisible(false);
        add.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        add = new javax.swing.JRadioButton();
        delete = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel00 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quanfield = new javax.swing.JTextField();
        alter = new javax.swing.JRadioButton();
        price = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tool Name :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Price :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        namefield.setBackground(new java.awt.Color(61, 61, 61));
        namefield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        namefield.setForeground(new java.awt.Color(255, 255, 255));
        namefield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, -1));

        priceField.setBackground(new java.awt.Color(61, 61, 61));
        priceField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        priceField.setForeground(new java.awt.Color(255, 255, 255));
        priceField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 170, -1));

        buttonGroup1.add(add);
        add.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD New Tool");
        add.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addItemStateChanged(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 140, 40));

        buttonGroup1.add(delete);
        delete.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE Existing Tool");
        delete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deleteItemStateChanged(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 170, 40));

        jButton1.setBackground(new java.awt.Color(85, 124, 104));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DONE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 120, 60));

        jLabel00.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel00.setForeground(new java.awt.Color(255, 255, 255));
        jLabel00.setText("ID :");
        jPanel3.add(jLabel00, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        idField.setBackground(new java.awt.Color(61, 61, 61));
        idField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        idField.setForeground(new java.awt.Color(255, 255, 255));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 120, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        quanfield.setBackground(new java.awt.Color(61, 61, 61));
        quanfield.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        quanfield.setForeground(new java.awt.Color(255, 255, 255));
        quanfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.add(quanfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 170, -1));

        buttonGroup1.add(alter);
        alter.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        alter.setForeground(new java.awt.Color(255, 255, 255));
        alter.setText("ADD Tool Quantity");
        alter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                alterItemStateChanged(evt);
            }
        });
        jPanel3.add(alter, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, 40));

        buttonGroup1.add(price);
        price.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Change Tool Price");
        price.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                priceItemStateChanged(evt);
            }
        });
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.jpeg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addItemStateChanged
        // TODO add your handling code here:
        if (add.isSelected()) {
            jLabel00.setVisible(false);
            idField.setVisible(false);
            namefield.setVisible(true);
            priceField.setVisible(true);
            quanfield.setVisible(true);
            jLabel17.setVisible(true);
            jLabel20.setVisible(true);
            jLabel2.setVisible(true);
        }
    }//GEN-LAST:event_addItemStateChanged

    private void deleteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deleteItemStateChanged
        // TODO add your handling code here:
        if (delete.isSelected()) {
            namefield.setVisible(false);
            priceField.setVisible(false);
            quanfield.setVisible(false);
            jLabel17.setVisible(false);
            jLabel20.setVisible(false);
            jLabel2.setVisible(false);
            jLabel00.setVisible(true);
            idField.setVisible(true);
        }
    }//GEN-LAST:event_deleteItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection c = null;
        int i=0;
        if(add.isSelected() && !namefield.getText().equals("") && !priceField.getText().equals("") && !quanfield.getText().equals(""))
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
                PreparedStatement ps = c.prepareStatement("insert into items values(?,?,?,?)");
                ps.setString(1, null);
                ps.setString(2, "tool");
                ps.setInt(3, Integer.parseInt(priceField.getText()));
                ps.setInt(4, Integer.parseInt(quanfield.getText()));
                ps.executeUpdate();
                
                PreparedStatement pst2 = c.prepareStatement("select id from items ORDER BY id DESC LIMIT 1");
                ResultSet rs = pst2.executeQuery();
                while(rs.next())
                {
                 i=rs.getInt("id");
                }
            
                PreparedStatement ps1 = c.prepareStatement("insert into tools values(?,?)");
                ps1.setInt(1,i);
                ps1.setString(2, namefield.getText());
                ps1.executeUpdate();
          
                c.close();
            }
            catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(delete.isSelected() && !idField.getText().equals(""))
        {
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
                PreparedStatement ps = c.prepareStatement("delete from items where id=?");
                ps.setInt(1, Integer.parseInt(idField.getText()));
                ps.execute();
                c.close();
            }
            catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
            {
                JOptionPane.showMessageDialog(this, e);
            }

        }
        else if(alter.isSelected() && !idField.getText().equals("") && !quanfield.getText().equals(""))
        {
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
                PreparedStatement ps4 = c.prepareStatement("update items set quantity = ? where id = ?");
                ps4.setInt(1, Integer.parseInt(quanfield.getText()));
                ps4.setInt(2, Integer.parseInt(idField.getText()));
                ps4.executeUpdate();
            }
            catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
            {
                JOptionPane.showMessageDialog(this, e);
            }

        }
        else if(price.isSelected() && !idField.getText().equals("") && !priceField.getText().equals(""))
        {
            try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement pst4 = c.prepareStatement("update items set Price = ? where id = ?");
            pst4.setInt(1, Integer.parseInt(priceField.getText()));
            pst4.setInt(2, Integer.parseInt(idField.getText()));
            pst4.executeUpdate();
            c.close();   
        } 
        catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Fill the missing data!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alterItemStateChanged
        // TODO add your handling code here:
        if(alter.isSelected())
        {
            idField.setVisible(true);
            jLabel00.setVisible(true);
            quanfield.setVisible(true);
            jLabel2.setVisible(true);
            namefield.setVisible(false);
            priceField.setVisible(false);
            jLabel17.setVisible(false);
            jLabel20.setVisible(false);
        }
    }//GEN-LAST:event_alterItemStateChanged

    private void priceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_priceItemStateChanged
        // TODO add your handling code here:
        idField.setVisible(true);
        priceField.setVisible(true);
        jLabel00.setVisible(true);
        namefield.setVisible(false);
        quanfield.setVisible(false);
        jLabel17.setVisible(false);
        jLabel2.setVisible(false);
        jLabel20.setVisible(true);
    }//GEN-LAST:event_priceItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            namefield.setText("");
            quanfield.setText("");
            priceField.setText("");
            idField.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton add;
    private javax.swing.JRadioButton alter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton delete;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField namefield;
    private javax.swing.JRadioButton price;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField quanfield;
    // End of variables declaration//GEN-END:variables
}
