/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class clayJFrame extends javax.swing.JFrame {

    /**
     * Creates new form clayJFrame
     */
    public clayJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl_580x430.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 570, 430));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(198, 198, 198));
        jTextArea1.setRows(5);
        jTextArea1.setText("Clay soils feel very sticky and rolls like \nplasticine when wet. They can hold more\ntotal water than most other soil types and \nalthough only about half of this is available \nto plants, crops seldom suffer from drought.\nThey swell when wetted and shrink when \ndried, so a certain amount of restructuring \ncan take place in these soils depending on \nweather conditions.\nThey lie wet in winter and so stock should be \ntaken off the land to avoid poaching \n(the compaction of soils by animals hooves).\nThey are very late in warming up in the spring\nbecause water heats up more slowly than \nmineral matter. They are normally fairly rich\n in potash, but are deficient in phosphates.\nClay soils usually need large infrequent \ndressings of lime.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 320, 500));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 198, 198));
        jLabel2.setText("Clay Soil Land");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(198, 198, 198));
        jLabel3.setText("Characteristics");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(198, 198, 198));
        jTextArea2.setRows(5);
        jTextArea2.setText("Aster (Symphyotrichum) \nBearded Iris (Iris germanica) \nBee Balm (Monarda) \nBlack Eyed Susan (Rudbeckia) \nButterfly Bush (Buddleia davidii) \nDaylily (Hemerocallis) \nEchinacea (Echinacea purpurea) \nHelenium (Helenium) \nJoe Pye Weed (Eupatorium) \nLiatris (Liatris) \nPhlox (Phlox) \nSedum (Sedum) \nViburnum (Viburnum plicatum) ");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 280, 500));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(198, 198, 198));
        jTextArea3.setRows(5);
        jTextArea3.setText("To improve your soil, you'll need to add 6 to \n8 inches of organic matter to the entire bed. \nYou can add any type of organic matter. \nGrass clippings (as long as they haven't been \ntreated with chemicals), shredded leaves, \nrotted manure, and compost are all perfect \nchoices. \nSpread the organic matter on top of the soil. \nHere's where the manual labor comes in. The \norganic matter needs to be mixed into the top \n6 to 12 inches of soil. Digging it in and mixing\nit with a shovel is a great way to do this, as it \nmoves a lot of earth without pulverizing the \nsoil particles the way tilling can. However, if \ndigging is just too hard on your back, using a \ntiller is a fine method.");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 330, 500));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(198, 198, 198));
        jLabel4.setText("What To Plant");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(198, 198, 198));
        jLabel5.setText("How To Improve");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
