
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class JFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame3
     */
    public JFrame3() {
        initComponents();

        jLabel1.setVisible(false);

        //idF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        newImg = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        tn = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Settings");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Quantity :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 70, 30));

        jButton1.setBackground(new java.awt.Color(71, 71, 112));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Add To Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 142, 80));

        newImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a3_2.jpg"))); // NOI18N
        jPanel1.add(newImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 162, 170, 153));

        jSpinner1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSpinner1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSpinner1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSpinner1MouseReleased(evt);
            }
        });
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 90, 40));

        tn.setEditable(false);
        tn.setBackground(new java.awt.Color(51, 51, 51));
        tn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        tn.setForeground(new java.awt.Color(255, 255, 255));
        tn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jPanel1.add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 127, 25));

        tt.setEditable(false);
        tt.setBackground(new java.awt.Color(51, 51, 51));
        tt.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        tt.setForeground(new java.awt.Color(255, 255, 255));
        tt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jPanel1.add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, 25));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("I.id :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 19, 26, -1));

        idF.setEditable(false);
        idF.setBackground(new java.awt.Color(51, 51, 51));
        idF.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(idF, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 16, 27, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("quantity max = 2 !! become a member to get more.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 280, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("NOTE :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("This is my free item");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jCheckBox1AncestorRemoved(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Sice you are a member, you are allowed to");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("choose one free item of your choice.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/as_690x520.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        double total = 0.0;
        double x = 0.0;
        int quan = 0;
        boolean allowed = true;
        java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
        DefaultTableModel modeltbl2 = (DefaultTableModel) NewJFrame.j.jTable22.getModel();

        if (NewJFrame.j.jLabel189.getText().equals("u") || NewJFrame.j.jLabel192.getText().equals("u")) {
            int i = 0;

            for (i = 0; i < modeltbl2.getRowCount(); i++) {
                //String name = modeltbl2.getValueAt(i, 2).toString();
                int id = Integer.parseInt(idF.getText());
                if (id == Integer.parseInt(modeltbl2.getValueAt(i, 0).toString())) {
                    int qq = Integer.parseInt(modeltbl2.getValueAt(i, 3).toString());
                    int q = Integer.parseInt(jSpinner1.getValue().toString());
                    int qqq = q + qq;

                    if (qqq > 2) {
                        JOptionPane.showMessageDialog(this, "you have reached the maximum quantity allowed for an item ('2'), become a member to get more");
                        allowed = false;
                        break;
                    }
                }

            }

        }
        if (allowed) {

            if (jSpinner1.getValue().toString().equals("0")) {
                JOptionPane.showMessageDialog(this, "Please select a Quantity");
            } else {
                if (jCheckBox1.isSelected()) {
                    modeltbl2.addRow(new Object[]{idF.getText(), tt.getText(), tn.getText(), 1, 0.01, date + "    ('FREE')"});
                    int a = NewJFrame.j.jTable22.getRowCount();
                    modeltbl2.moveRow(a - 1, a - 1, 0);
                } else {

                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");

                        PreparedStatement ps = con.prepareStatement("select Price from items where id = " + Integer.parseInt(idF.getText()));
                        ResultSet rs = ps.executeQuery();
                        while (rs.next()) {
                            x = rs.getDouble("Price");
                            total = x * Integer.parseInt(jSpinner1.getValue().toString());
                        }
                    } catch (NumberFormatException | SQLException e) {
                        System.out.println(e);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(JFrame3.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    int i = 0;

                    for (i = 0; i < modeltbl2.getRowCount(); i++) {
                        //String name = modeltbl2.getValueAt(i, 2).toString();
                        int id = Integer.parseInt(idF.getText());
                        if (id == Integer.parseInt(modeltbl2.getValueAt(i, 0).toString())) {
                            int q = Integer.parseInt(jSpinner1.getValue().toString());
                            int qq = Integer.parseInt(modeltbl2.getValueAt(i, 3).toString());
                            modeltbl2.setValueAt(q + qq, i, 3);
                            double t = x * Integer.parseInt((modeltbl2.getValueAt(i, 3).toString()));
                            modeltbl2.setValueAt(t, i, 4);
                            break;
                        }

                    }
                    if (i == modeltbl2.getRowCount()) {

                        modeltbl2.addRow(new Object[]{idF.getText(), tt.getText(), tn.getText(), Integer.parseInt(jSpinner1.getValue().toString()), total, date});
                    }
                }

                JOptionPane.showMessageDialog(this, "Item added to cart successfully..!");
                dispose();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked

    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jSpinner1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MousePressed

    private void jSpinner1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseReleased

    private void jSpinner1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseEntered

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        Connection c = null;
        int quan = 0;

        int selected = Integer.parseInt(jSpinner1.getValue().toString());
        try {

            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            PreparedStatement ps3 = c.prepareStatement("select quantity from items where id=?");
            ps3.setString(1, idF.getText());
            ResultSet rs = ps3.executeQuery();

            while (rs.next()) {

                quan = rs.getInt("quantity");

            }
            if (quan == 0) {
                JOptionPane.showMessageDialog(this, "Item Sold Out!!");
                jButton1.setEnabled(false);
            } else if (selected > quan) {
                JOptionPane.showMessageDialog(this, "there is no enough quantity in the store as you selected, please select less quantity");
                jButton1.setEnabled(false);
            } else {
                jButton1.setEnabled(true);

            }

        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jSpinner1.setValue(1);
            jSpinner1.setEnabled(false);
            int a = NewJFrame.j.jTable22.getRowCount();
            for (int j = 0; j < a; j++) {
                if (NewJFrame.j.jTable22.getValueAt(j, 4).toString().equals("0.01")) {
                    JOptionPane.showMessageDialog(this, "you already selected your free item");
                    jCheckBox1.setEnabled(false);
                }
            }

        } else {
            jSpinner1.setValue(0);
            jSpinner1.setEnabled(true);
            jCheckBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCheckBox1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1AncestorRemoved

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idF;
    public javax.swing.JButton jButton1;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JSpinner jSpinner1;
    public javax.swing.JLabel newImg;
    public javax.swing.JTextField tn;
    public javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
