
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class startJFrame extends javax.swing.JFrame {

    /**
     * Creates new form startJFrame
     */
    public startJFrame() {
        initComponents();
        jLabel6.setVisible(false);
        jButton2.setOpaque(false);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        sign = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("username :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 119, 80, 30));

        nameField.setBackground(new java.awt.Color(102, 102, 102));
        nameField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(204, 204, 204));
        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 4, true));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 200, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 219, 71, 30));

        passField.setBackground(new java.awt.Color(102, 102, 102));
        passField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 4, true));
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 30));

        sign.setBackground(new java.awt.Color(51, 51, 51));
        sign.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        sign.setForeground(new java.awt.Color(204, 204, 204));
        sign.setText("SIGN IN");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });
        sign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signKeyPressed(evt);
            }
        });
        jPanel2.add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("admin sigin page");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("__________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(191, 0, 0));
        jLabel6.setText("password is at least 8 characters");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 226, 190, 20));

        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("forgot password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        // TODO add your handling code here:
       Connection conn = null;
        String username = null;
        String password = null;
        String firstname = null;
        String role = null;
        int id = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            try {

                PreparedStatement ps = conn.prepareStatement("select userID,username,password from accounts where username='" + nameField.getText() + "' and password= '" + passField.getText() + "'");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    username = rs.getString("username");
                    password = rs.getString("password");
                    id = rs.getInt("userID");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            try {
                PreparedStatement ps2 = conn.prepareStatement("select firstname,role from users where id=" + id);
                ResultSet rs2 = ps2.executeQuery();
                while (rs2.next()) {
                    firstname = rs2.getString("firstname");
                    role = rs2.getString("role");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(memJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (nameField.getText().equals(username) && passField.getText().equals(password) && (role.equals("admin") || role.equals("owner"))) {
            alterJFrame ajf = new alterJFrame();
            ajf.jj.setText("HEY " + firstname.toUpperCase() + ",");
            if(role.equals("admin"))
            {
                ajf.jMenuItem5.setEnabled(false);
            }
            dispose();
            ajf.show();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid adminname or Password");
            nameField.setText(null);
            passField.setText(null);
        }

    }//GEN-LAST:event_signActionPerformed

    private void signKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_signKeyPressed

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        // TODO add your handling code here:
        if(passField.getText().length()<8)
        {
            jLabel6.setVisible(true);
            sign.setEnabled(false);
        }
        else if(passField.getText().length()>7)
        {
            jLabel6.setVisible(false);
            sign.setEnabled(true);
        }
    }//GEN-LAST:event_passFieldKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection c = null;
        String pn = JOptionPane.showInputDialog("enter your phone number :");
        String phone = null;
        String ques = null;
        String answer = null;
        String answer2 = null;
        String newPass = null;
        int again=1;
        int pointer = 0;

        int index = 0;
        int id = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SummerProject", "root", "");
            try {

                PreparedStatement ps = c.prepareStatement("select id,phoneNumber from users where phoneNumber = '" + pn + "'");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    phone = rs.getString("phoneNumber");
                    id = rs.getInt("id");
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
            if (pn.equals(phone)) {
                try {
                    PreparedStatement ps2 = c.prepareStatement("select securityQuestion from accounts where userID = " + id);
                    ResultSet rs2 = ps2.executeQuery();
                    while (rs2.next()) {
                        ques = rs2.getString("securityQuestion");
                    }
                } catch (SQLException e) {

                }
                Object[] questions = {"what is your phone's first password?", "what is your favourite nickname?", "how many girlfriends you have had since your first one?", "what is your favourite second country?"};
                JComboBox comboBox = new JComboBox(questions);
                comboBox.setSelectedItem(null);
                JOptionPane.showMessageDialog(null, comboBox, "choose your security question", JOptionPane.QUESTION_MESSAGE);
                answer = JOptionPane.showInputDialog("answer :");
                index = comboBox.getSelectedIndex();
                if(index==0)
                {
                    answer2 = answer + "(Q1)";
                    pointer=1;

                }
                else if(index==1)
                {
                    answer2 = answer + "(Q2)";
                    pointer=1;
                }
                else if(index==2)
                {
                    answer2 = answer + "(Q3)";
                    pointer=1;
                }
                else if(index==3)
                {
                    answer2 = answer + "(Q4)";
                    pointer=1;
                }
                else
                {
                    pointer=0;
                }
                if(pointer==1)
                {
                    if (ques.equalsIgnoreCase(answer2)) {

                        for(int i=0;i<again;i++)
                        {
                            newPass = JOptionPane.showInputDialog("Enter your new password :");
                            if (!newPass.equals("") && newPass.length() > 7) {

                                try {
                                    PreparedStatement ps3 = c.prepareStatement("update accounts set password = '" + newPass + "'" + "where userID = " + id);
                                    ps3.executeUpdate();
                                    JOptionPane.showMessageDialog(this, "password changed, make sure to save it for next time");
                                } catch (HeadlessException | SQLException e) {
                                    System.out.println(e);
                                }
                                break;

                            }
                            else {
                                JOptionPane.showMessageDialog(this, "the password must contain at least 8 characters");
                                again++;
                            }
                        }

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Incorrect answer or question");
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "incorrect phone number");
            }

        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField nameField;
    public javax.swing.JTextField passField;
    public javax.swing.JButton sign;
    // End of variables declaration//GEN-END:variables
}
